version: "2.4"

services:
  mysql:
    image: mysql:8.0
    container_name: flask_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
    volumes:
      - two-tier-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 60s
    networks:
      - two-tier-network

  flask:
    image: flask-app:latest
    container_name: flask_app
    environment:
      MYSQL_HOST: mysql
      MYSQL_DB: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - two-tier-network

volumes:
  two-tier-volume:

networks:
  two-tier-network:

